import{a as v,S as q,i as c}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const P="51676197-587b7604ca68e3bcd271cfabc",M="https://pixabay.com/api/";async function u(o,t){const n={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await v.get(M,{params:n})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more"),B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r,views:a,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img src="${n}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${a}</p>
          <p><b>Comments:</b> ${w}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function E(){f.innerHTML=""}function h(){m.classList.remove("hidden")}function y(){m.classList.add("hidden")}function b(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}function $(){const o=document.querySelector(".gallery .gallery-item");o&&setTimeout(()=>{const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})},200)}const R=document.querySelector(".form"),O=document.querySelector(".load-more");let l="",i=1,d=0;R.addEventListener("submit",x);O.addEventListener("click",T);async function x(o){if(o.preventDefault(),l=o.currentTarget.elements["search-text"].value.trim(),!l){c.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}E(),i=1,h(),L();try{const t=await u(l,i);if(t.hits.length===0){c.info({title:"No Results",message:"Sorry, no images found. Please try again!",position:"topRight"});return}d=Math.ceil(t.totalHits/15),g(t.hits),i<d&&b()}catch{c.error({title:"Error",message:"Something went wrong!",position:"topRight"})}finally{y()}}async function T(){i+=1,h(),L();try{const o=await u(l,i);g(o.hits),$(),i<d?b():c.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})}catch{c.error({title:"Error",message:"Something went wrong!",position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
